"""
Context Quality Scorer — Grades the quality of user-provided context.

Computes a letter grade (A-F) based on what context the user provided
and how substantive it is. This grade is embedded in the report header
and run metadata so readers know how much to trust the findings.

Grading rubric:
  A  — World model + transcripts + customer list (all substantive)
  B  — World model + at least one of transcripts/customer list
  C  — World model only (or transcripts + customer list without world model)
  D  — Minimal context (only one thin file, or auto-generated world model)
  F  — No context files at all (pure LLM imagination)
"""
from typing import Dict, Any, List, Tuple

from engines.logging_config import get_logger

logger = get_logger(__name__)

# Minimum character thresholds for "substantive" content
MIN_WORLD_MODEL_CHARS = 500
MIN_TRANSCRIPTS_CHARS = 300
MIN_CUSTOMER_LIST_CHARS = 200


def _check_file_quality(path: str | None, min_chars: int) -> Tuple[bool, int]:
    """Check if a context file exists and has substantive content."""
    if not path:
        return False, 0

    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        char_count = len(content.strip())
        return char_count >= min_chars, char_count
    except Exception:
        return False, 0


def compute_context_quality(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compute a context quality score for the simulation.

    Args:
        config: The fully-resolved simulation config dict.

    Returns:
        Dict with:
          - grade: str (A, B, C, D, F)
          - score: float (0.0-1.0)
          - details: dict of what was/wasn't provided
          - warnings: list of actionable warnings
          - report_caveat: str to include in the report header
    """
    warnings: List[str] = []
    details = {}

    # Check world model
    wm_path = config.get("world_model_path")
    wm_generated = config.get("_generated_world_model", False)
    wm_ok, wm_chars = _check_file_quality(wm_path, MIN_WORLD_MODEL_CHARS)

    if wm_generated:
        details["world_model"] = "auto-generated"
        warnings.append(
            "World model was auto-generated by LLM. Provide a real world model "
            "with industry data, competitor analysis, and market sizing for more "
            "accurate personas."
        )
    elif wm_ok:
        details["world_model"] = f"provided ({wm_chars:,} chars)"
    elif wm_path:
        details["world_model"] = f"provided but thin ({wm_chars:,} chars)"
        warnings.append(
            f"World model file has only {wm_chars:,} characters. Aim for 500+ "
            "characters with specific industry data, market sizing, and "
            "competitive landscape for better grounding."
        )
    else:
        details["world_model"] = "not provided"

    # Check transcripts
    tx_path = config.get("transcripts_path")
    tx_ok, tx_chars = _check_file_quality(tx_path, MIN_TRANSCRIPTS_CHARS)

    if tx_ok:
        details["transcripts"] = f"provided ({tx_chars:,} chars)"
    elif tx_path:
        details["transcripts"] = f"provided but thin ({tx_chars:,} chars)"
        warnings.append(
            f"Transcripts file has only {tx_chars:,} characters. Even 2-3 real "
            "customer conversations dramatically improve persona realism."
        )
    else:
        details["transcripts"] = "not provided"
        warnings.append(
            "No real customer transcripts provided. Personas will be based on "
            "LLM assumptions about customer language and objections, not real data."
        )

    # Check customer list
    cl_path = config.get("customer_list_path")
    cl_ok, cl_chars = _check_file_quality(cl_path, MIN_CUSTOMER_LIST_CHARS)

    if cl_ok:
        details["customer_list"] = f"provided ({cl_chars:,} chars)"
    elif cl_path:
        details["customer_list"] = f"provided but thin ({cl_chars:,} chars)"
    else:
        details["customer_list"] = "not provided"

    # Compute grade
    has_real_wm = wm_ok and not wm_generated
    has_tx = tx_ok
    has_cl = cl_ok

    context_count = sum([has_real_wm, has_tx, has_cl])

    if has_real_wm and has_tx and has_cl:
        grade = "A"
        score = 1.0
    elif has_real_wm and (has_tx or has_cl):
        grade = "B"
        score = 0.75
    elif has_real_wm or (has_tx and has_cl):
        grade = "C"
        score = 0.50
    elif context_count >= 1 or wm_generated:
        grade = "D"
        score = 0.25
    else:
        grade = "F"
        score = 0.0
        warnings.append(
            "NO CONTEXT PROVIDED. This simulation is running on pure LLM "
            "imagination. Results are directional at best. Provide a world "
            "model, transcripts, or customer list to dramatically improve quality."
        )

    # Build report caveat
    grade_descriptions = {
        "A": "grounded in verified market data, real customer transcripts, and customer profiles",
        "B": "grounded in verified market data and partial real customer context",
        "C": "partially grounded in provided context but missing key data sources",
        "D": "minimally grounded — most persona behavior is LLM-estimated, not data-driven",
        "F": "ungrounded — all persona behavior is LLM-generated with no real customer data",
    }

    report_caveat = (
        f"**Context Quality: {grade}** — This simulation is {grade_descriptions[grade]}. "
        f"Context files: world model ({details['world_model']}), "
        f"transcripts ({details['transcripts']}), "
        f"customer list ({details['customer_list']})."
    )

    if grade in ("D", "F"):
        report_caveat += (
            " Findings should be treated as hypotheses for real-world validation, "
            "not as market evidence."
        )

    result = {
        "grade": grade,
        "score": score,
        "details": details,
        "warnings": warnings,
        "report_caveat": report_caveat,
    }

    logger.info("Context quality: grade=%s, score=%.2f", grade, score)
    for w in warnings:
        logger.warning("Context: %s", w)

    return result
